---

general:
  mcc: '001'
  mnc: '01'

nodes:
  - name: cplane01
    ip: 192.168.122.100/24
    type: control

  - name: uplane01
    type: control
    ip: 192.168.122.200/24
    dnn_networks:
      name: internet
      address: 10.45.0.1/16
