network:
    version: 2
    ethernets:
        eth01:
            match:
                macaddress: 52:54:00:f9:cd:59
            addresses: ['192.168.122.100']
            dhcp: false
            gateway4: 192.168.122.1
            nameservers:
                addresses: 8.8.8.8
            set-name: eth01